from os import getenv

TELEGRAM_TOKEN = getenv('APP_TELEGRAM_TOKEN')

POSTGRES_USER = getenv('POSTGRES_USER')
POSTGRES_DB = getenv('POSTGRES_DB')
POSTGRES_PORT = getenv('POSTGRES_PORT')
POSTGRES_PW = getenv('POSTGRES_PW')
POSTGRES_HOST = getenv('POSTGRES_HOST')